### ISSUE TITLE
Problème avec virtualenv lors de la montée de version

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/UsersHub#100]
Lorsque je passe de la 2.1.0 à la 2.1.1 en suivant la doc, une première erreur renvoie /usr/bin/python3: No module named virtualenv

S'en suit une série de soucis, et pas d'appli à l'arrivée. 

En installant virtual env à la main (pip install virtualenv, et la même en sudo), je m'appercois que par défaut il va l'installer dans usr/lib/python2.7... et me répond que le pré-recquis est déjà satisfait. Mais pas au bon endroit... 

Est-ce possible de forcer l'installation dans python3 dans l'install_app ?

**Comment by TheoLechemia** [comment]
Essaye de lancer cette commande: `pip3 install virtualenv==20.0.1`

**Comment by DonovanMaillard** [comment]
Ca ne fonctionne pas non plus, il me renvoie 

pip3 : commande introuvable

J'ai donc tenté de réinstaller python3-pip : 
sudo apt-get remove python3-pip
sudo apt-get install python3-pip

Mais la commande me retourne une erreur Err:1 http://deb.debian.org/debian stretch/main amd64 python3-pip all 9.0.1-2
  404  Not Found [IP : 151.101.36.204 80]

Il manquerait une source?

**Comment by TheoLechemia** [comment]
C'est bien possible. Tu es sur debian 9 ou 10 ?

**Comment by DonovanMaillard** [comment]
Sur debian 9. 

J'ai bien ces sources dans ma liste. Ca semble pas venir d'ici.

**Comment by DonovanMaillard** [comment]
apt-get update et apt-get upgrade ont pu résoudre le soucis, j'ai pu installer virtualenv sans soucis ;) Merci!

**Comment by camillemonchicourt** [comment]
OK, à voir si il faut ajouter ça dans la doc ou bien dans les scripts d'installation pour éviter à d'autres le soucis ?

**Comment by DonovanMaillard** [comment]
Ajouts faits dans mon cas, si pertinent à ajouter dans le script : 

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3-pip
sudo pip3 install virtualenv==20.0.1
```

**Comment by camillemonchicourt** [comment]
Indiqué dans le Changelog de UsersHub aussi, si jamais les utilisateurs mettent à jour UH avant GN : https://github.com/PnX-SI/UsersHub/commit/dba2310ea0f8b8a3c920b3e73b0e95c092545425
