### ISSUE TITLE
Version MarkupSafe Et Debian10

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/UsersHub#103]
Sous Debian 10, l'installation d'Usershub a plantée avec la version 1.0 de MarkupSafe, en modifiant dans requirements.txt pour la version 1.1 l'installation se déroule sans accroc. 
https://github.com/PnX-SI/UsersHub/blob/355586421121d0654a61f492ab06404e0715926b/requirements.txt#L16

C'est aussi évoqué ici : https://github.com/pallets/markupsafe/issues/57

Edit : L'installation de MarkupSafe==0.23 pour taxhub s'est bien déroulée

**Comment by jbrieuclp** [comment]
Y a moyen de faire un lien entre ce ticket et https://github.com/PnX-SI/GeoNature/issues/881 sans pour autant poster un truc ?

**Comment by camillemonchicourt** [comment]
Corrigé dans 2.1.2
