### ISSUE TITLE
Pas de création de framework / jdd automatique avec validation des demandes sur usershub

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/UsersHub#110]
Bonjour,

Lorsque je valide une demande de création de compte utilisateur _via_ le lien reçu par mail (https://geonature.mondomaine.fr/api/users/confirmation?token=xxxx) le framework et le JDD personnel de l'utilisateur sont bien créés automatiquement.

Par contre, si je valide _via_ UsersHub (je suis sur la  v2.1.2), onglet "demandes de compte", les framework + JDD ne sont pas créés. 

Et si je valide un compte _via_ UsersHub, impossible de valider les autres comptes de la liste avec le lien reçu par mail. Cela retourne un : 
`{"msg": "pas d'utilisateur trouv\u00e9 avec le token user demand\u00e9"}
`

Donc pas d'autre choix que de tout valider avec UsersHub (et pas de JDD automatique à la clé !). 

Quelqu'un d'autre à remarqué ce comportement ? Il est normal ? ou faut que je cherche un problème du côté de mes applis ?

**Comment by DonovanMaillard** [comment]
Probablement ce qui m'était arrivé quand j'ai déposé [ce ticket](https://github.com/PnX-SI/GeoNature/issues/862) coté GeoNature, mais en effet ça a plutôt sa place ici

**Comment by TheoLechemia** [comment]
Bonjour,
Pour le fait que seul le lien vers le mail crée les JDD: c'est normal, car c'est une action GeoNature, qui elle même appel une action Usershub. On ne peut pas réaliser l'action côté Usershub.
Et lorsqu'on a validé le compte côté Userhub, l'utilisateur "temporaire" (et donc le token) qui avait été créé est supprimé. Donc le lien dans le mail ne fonctionne plus.
Si vous voulez que les JDD soient bien créés, il faut valider uniquement via le mail.

**Comment by camillemonchicourt** [comment]
Possible avec la version 2.1.3 de UsersHub et la 2.5.0 de GeoNature.
