### ISSUE TITLE
Gestion des emails et actions des applis dans UsersHub

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/UsersHub#115]
Il apparait nécessaire de trouver un solution pour gérer côté UsersHub les actions spécifiques à une application à réaliser après une validation de compte utilisateur en attente.
Cela permettrait:
- d'éviter les problèmes indiqués dans les tickets #110 et PnX-SI/GeoNature#862
- de renvoyer un email à l'utilisateur pour lui confirmer sa validation quand elle est faite via le lien présent dans l'email envoyé à l'admin et pointant GeoNature ou via l'interface d'UsersHub.

Autrement dit, actuellement l'envoi d'email ne se fait que via GeoNature. De même, les actions de création de cadre d’acquisition (CA) et de jeux de données (JDD) personnels sont réalisées uniquement dans GeoNature. Si la validation de compte est faite sur UsersHub aucune de ces actions ne sera réalisées.

Une idée pour résoudre ces problèmes pourrait être d'ajouter 2 champs à la table _utilisateurs.temp_users_ permettant de stocker:
  - `app_source`: le nom de code de l'application à l'origine de la création du compte utilisateur. => existe déjà avec le champ `id_application`
  - `app_callback_url`: l'URL à appeler du côté de l'application à rappeler suite à une création de compte côté UsersHub. => finalement nommé `confirmation_url`

Cette modification entrainerait à priori les tâches suivantes:
- [x] modification du SQL de création du schéma "utilisateurs" concernant la table  _utilisateurs.temp_users_
- [x] ajout au script de migration de UsersHub la création <del>des 2 nouveaux champs</del> d'un nouveau champ
- [x] modification du code UsesHub pour prendre en compte l'URL de rappel (callback)
- [x] <del>modification de l'interface pour ajouter l'affichage du champ `app_source`</del> => déjà le cas

@camillemonchicourt @TheoLechemia  @amandine-sahl est ce que cette solution vous semble envisageable ? Avez vous une autre proposition ?

**Comment by camillemonchicourt** [comment]
Ouais pourquoi pas, ça éviterait de devoir déporter l'envoi d'email etc au niveau de UsersHub.
