### ISSUE TITLE
Problème de mise à jour 2.1.2 vers 2.1.3

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/UsersHub#120]
Bonjour,

Je viens de mettre à jour UsersHub vers la version 2.1.3. Après mise à jour, l'interface se charge bien, mais impossible de se connecter avec n'importe quel couple login/mdp. A priori, ces couples n'ont pas été effacés pendant la mise à jour car ils fonctionnent encore pour se connecter à l'application GeoNature. Quelqu'un a-t-il une idée de ce qui a pu se passer ?

**Comment by TheoLechemia** [comment]
Quelle est l'erreur remonté dans le console ? Dans les logs ?

**Comment by geobrun** [comment]
Pas d'erreur a priori, seulement une ligne toute à la fin disant que le log n'a pas pu être créé...

Ce qui est curieux, c'est que cette erreur persiste peu importe la version de UsersHub. Car si je remets le répertoire "old" de la version 2.1.2 comme étant le bon répertoire de UsersHub, mes connexions ne fonctionnent pas non plus. Je peux relancer une mise à jour vers la version 2.1.3 pour retrouver le message d'erreur concernant les logs ?

**Comment by camillemonchicourt** [comment]
Je suis pas certain que le retour en arrière de version se fasse comme ça, il doit falloir relancer une commande.

Peux-tu indiquer le retour de <URL_UsersHub>/pypn/auth/login ?

**Comment by geobrun** [comment]
Je reçois une erreur avec l'URL en question : "The method is not allowed for the requested URL. "

Je suis en train de regarder dans mes tables PostgreSQL s'il n'y a pas quelque chose qui cloche dans les autorisations sur l'application UsersHub mais je ne vois rien pour le moment, étant donné que j'ai fait des modifications dessus vendredi dernier. Des fois que j'aurais cassé quelque chose en passant, même si ça fonctionnait bien la dernière fois que je me suis connecté il me semble !

**Comment by amandine-sahl** [comment]
"The method is not allowed for the requested URL. " => Il faut faire un post et non pas un get

**Comment by geobrun** [comment]
Merci pour le retour ! Mais comment je fais ça ?

**Comment by TheoLechemia** [comment]
Il faudrait regarder les logs du backend (usershub/var/log) et/ou les logs de la console du navigateur

**Comment by geobrun** [comment]
Visiblement, il s'agit bien d'un POST car voilà le message d'erreur dans lefichier "access_uhv2.log" :
"POST /pypn/auth/login HTTP/1.1" 490 52 "<adressedemonserveur>/usershub/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"

**Comment by TheoLechemia** [comment]
c'est plutot le fichier "error_uhv2" qu'il faut !

**Comment by geobrun** [comment]
Je ne l'avais pas mis car je n'avais rien vu de spécial dedans :
`Starting usershub2`
`/home/geonatureadmin/usershub`
`[2020-12-18 15:15:14 +0000] [1380] [INFO] Starting gunicorn 19.9.0`
`[2020-12-18 15:15:14 +0000] [1380] [INFO] Listening at: http://0.0.0.0:5001 (1380)`
`[2020-12-18 15:15:14 +0000] [1380] [INFO] Using worker: sync`
`[2020-12-18 15:15:14 +0000] [1505] [INFO] Booting worker with pid: 1505`
`[2020-12-18 15:15:14 +0000] [1506] [INFO] Booting worker with pid: 1506`
`[2020-12-18 15:15:14 +0000] [1507] [INFO] Booting worker with pid: 1507`
`[2020-12-18 15:15:14 +0000] [1509] [INFO] Booting worker with pid: 1509`

**Comment by amandine-sahl** [comment]
Pourriez vous nous indiquer le résultat de 
```
curl 'https://appli.cevennes-parcnational.net/usershub/pypn/auth/login' \
    -H "Content-Type: application/json" \
    --data '{"id_application":"1","login":"test","password":"test"}'
```

**Comment by geobrun** [comment]
Merci pour ces indications Amandine ! En revenant sur ce problème ce matin, le message d'erreur que j'ai reçu suite à la commande Curl m'a fait repensé aux modifications que j'avais effectuées il y a quelques semaines dans les comptes de UsersHub. J'avais oublié que j'avais modifié le mot de passe du compte administrateur... Mea culpa, désolé de vous avoir fait perdre du temps !
