### ISSUE TITLE
Importer des organismes ou des utilisateurs depuis un fichier CSV ?

### ISSUE THREAD

**Issue by Heg0Damask** [PnX-SI/UsersHub#123]
Bonsoir,
est il possible d'importer une liste d'organisme via un fichier CSV avec nom_organisme,adresse_organisme,...
Même question pour les utilisateurs ?
merci

**Comment by camillemonchicourt** [comment]
Il n'existe actuellement pas d'interface d'import dans UsersHub mais c'est assez simple à importer directement dans la base de données depuis un CSV ou autre.

**Comment by Heg0Damask** [comment]
@camillemonchicourt : merci beaucoup je vais faire comme ça.
