### ISSUE TITLE
problème https usershub

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/UsersHub#131]
Bonjour,

J'ai installé une instance geonature sur un nouveau serveur, j'ai défini des sous-domaines et j'ai mis en place les certificats pour une connexion en https. 
Tout fonctionne bien pour geonature et taxhub, mais usershub ne fonctionne pas.
usershub.reserves-naturelles.org renvoie directement sur https://212.83.185.127/usershub/users/list et produit une erreur 404.

Je ne vois pas ce qui pose problème. Est-ce que quelqu'un a déjà eu un problème similaire ?

**Comment by camillemonchicourt** [comment]
A priori c'est pas un soucis UsersHub, mais un soucis Apache.
Peux-tu donner tes configurations Apache ?

**Comment by RNF-SI** [comment]
`# Configuration UsersHub avec sous-domaine et https

<VirtualHost *:80>
      ServerName usershub.reserves-naturelles.org

      RewriteEngine on
      RewriteCond %{HTTPS} !on
      RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:443>
        ServerName usershub.reserves-naturelles.org

            # Configuration uhv2
            <Location />
                    ProxyPass  http://127.0.0.1:5001/ retry=0
                    ProxyPassReverse  http://127.0.0.1:5001/
            </Location>
            #FIN Configuration uhv2

        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/usershub.reserves-naturelles.org/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/usershub.reserves-naturelles.org/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/usershub.reserves-naturelles.org/chain.pem
        SSLProtocol all -SSLv2 -SSLv3
        SSLHonorCipherOrder on
        SSLCompression off
        SSLOptions +StrictRequire
        SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
        Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"

</VirtualHost>
#FIN configuration UsersHub`

Dans le fichier usershub/config/settings.ini l'URL de l'application est la suivante : 
url_application=http://212.83.185.127/usershub

Ne faut-il pas modifier ça  par url_application=http://usershub.reserves-naturelles.org ?

**Comment by camillemonchicourt** [comment]
Si bien sur, il faut aussi bien renseigner ton settings.ini avec la bonne URL, c'est ça ton soucis.

**Comment by joelclems** [comment]
à changer dans le config.py aussi

**Comment by RNF-SI** [comment]
Effectivement ça marche beaucoup mieux, merci ! 
Peut-être juste le préciser dans la doc du coup, ou alors je l'ai loupé...
