### ISSUE TITLE
Rendre configurable la durée avant suppression automatique d'une demande de compte

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/UsersHub#136]
Il y a une suppression automatique des entrées de la table `utilisateurs.temp_users` fixée à 7 jours :
https://github.com/PnX-SI/UsersHub/blob/master/app/api/route_register.py#L92-L96

Il serait intéressant de pouvoir rendre cette valeur configurable.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.4.1.
