### ISSUE TITLE
Créer des utilisateurs via une API

### ISSUE THREAD

**Issue by Heg0Damask** [PnX-SI/UsersHub#138]
Bonjour,

Serait il possible de créer des utilisateurs directement via l'API ? J'ai une liste d'utilisateurs dans un fichier CSV avec des coordonnées j'aimerais les intégrer directement dans usershub. Existe t'il une doc ou une procédure quelque part qui pourrait m'aider ?

merci

**Comment by TheoLechemia** [comment]
L'API de Usershub permet de faire ça. Ici un exemple de de GeoNature qui utilise cette API: https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/core/users/routes.py#L269
Mais elle n'est pas aussi simple que ça, car pour des raison de sécurité on crée l'utilisateur dans un table temporaire, et un mécanisme de vérification (via un token), permet de basculer l'utilisateur de la table temporaire à la table `utilisateurs.t_roles`.
Si vous avez un CSV je vous conseil du bon vieux SQL di'nsertion dans la table `utilisateurs.t_roles`. Si c'est pour une fonctionnalité applicative, pourquoi pas utiliser l'API

**Comment by Heg0Damask** [comment]
Merci, je viens d'essayer ça a l'air bon avec une requête SQL. J'ai également alimenter la table cor_roles en parallèle de la même manière.
Est ce qu'il pourrait y avoir un effet de bord quelque part en utilisant ce genre de procédure pour intégrer des utilisateurs ?

**Comment by TheoLechemia** [comment]
Non pas d'effet de bord.

**Comment by Heg0Damask** [comment]
merci beaucoup
