### ISSUE TITLE
Restauration utilisateurs install globale

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/UsersHub#139]
Bonjour,

# Description du problème rencontré

Je parcourais usershub et suite à une modification je n'arrive plus à me logger en tant qu'admin ou via un admin que j'ai créé.

Voici mes étapes : 

* Connexion à usershub en tant que admin/admin
* Création d'un user et ajout dans grp_admin
* Decconnexion
* Connexion avec le nouveau user créé
* Modification des droits du user en cours d'utilisation >> suppression groupe admin du user

Depuis je n'arrive plus à me reconnecter à usershub via admin/admin ou via le user créé. Je ne suis plus certain à 100% de la manipulation faite, vu que je ne peux pas me reconnecter pour reproduire avec un autre user.

La connexion à /geonature est également impossible.

Un restart des serveurs à permis de retrouver la connexion admin à /geonature mais pas avec le user créé.

# Erreur

409 POST
Le message indique que l'utilisateur admin ou l'utilisateur créé n'existent pas.

# Question

Comment réinstaller par défaut la DB (retourné à l'état install global) ?

Un .backup est-il disponible dans les sources Git ?

# Environnement

Dernière version Installation Globale
Debian 10

Merci.

**Comment by lpofredc** [comment]
S'il s'agit juste de restaurer le mot de passe de l'admin, il s'agit d'un mot de passe crypté. un mot de passe en clair en bdd ne fonctionnera pas.
Pour le mot de passe `admin` du compte `admin`, c'est le texte suivant à renseigner dans le champ `pass_plus`.
```
$2y$13$TMuRXgvIg6/aAez0lXLLFu0lyPk4m8N55NDhvLoUHh/Ar3rFzjFT.
```
https://github.com/PnX-SI/UsersHub/blob/0f7b580f75f72050af1da79df0ef5072712daa00/data/usershub-dataset.sql#L21-L22

**Comment by Gaetanbrl** [comment]
en effet @lpofredc c'est cette requête je comptais intégrer avec le mot de pass encrypté.

Je vais lancer la requête pour fixer l'accès admin et ensuite reproduire pour voir ce qui a pu provoquer ce problème...

**Comment by Gaetanbrl** [comment]
Après inspection, c'est le group Grp_admin qui était manquant.

J'ai donc rajouté le groupe mais pas mieux, le user admin semble introuvable alors qu'il est bien dans la table avec le mdp / login : 

```
Request URL: http://192.xxxxxx/usershub/pypn/auth/login
Request Method: POST
Status Code: 490 UNKNOWN
{"type": "login", "msg": "No user found with the username \"admin\" for the application with id \"1\""}
```

![image](https://user-images.githubusercontent.com/16317988/129001895-334942f4-56ea-436c-8a8f-4fc034a89275.png)

**Comment by Gaetanbrl** [comment]
Après passage des requêtes suivantes, le group admin est rétabli et la connexion à /usershub en admin est OK : 

```
INSERT INTO t_roles (groupe, id_role, identifiant, nom_role, prenom_role, desc_role, pass, email, date_insert, date_update, id_organisme, remarques) VALUES 
(true, 9, NULL, 'Grp_admin', NULL, 'Tous les administrateurs', NULL, NULL, NULL, NULL, NULL, 'Groupe à droit total');

INSERT INTO utilisateurs.cor_roles (id_role_groupe, id_role_utilisateur) VALUES 
(9, 1);

INSERT INTO utilisateurs.cor_role_app_profil (id_role, id_application, id_profil) VALUES
(9, 1, 6) --admin UsersHub;
```

Par contre la connexion avec le user créé précédemment n'est toujours pas rétablie. Soit je le recréé soit il doit manquer l'inscription de ce user dans une table pour que la relation se réalisent bien.

**Comment by Gaetanbrl** [comment]
la suppression + création d'un nouveau user fonctionne.
Je clos le ticket.
