### ISSUE TITLE
Création utilisateur sans mot de passe 

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/UsersHub#140]
Lors de la création d'un utilisateur, il est possible de ne pas ajouter de mot de passe.

Ne serait-il pas intéressant de forcer l'ajout d'un mot de passe par défaut dés la création ?

**Comment by lpofredc** [comment]
Pas nécessairement (en tout cas dans ma situation), on peut avoir besoin de créer des utilisateurs sans nécessité pour eux de se connecter aux applications (par exemple pour des observateurs secondaires, des partenaires, etc.). Ce n'est pas non plus utile pour des roles parents.

**Comment by Gaetanbrl** [comment]
Merci du retour, dans ce cas ce n'est pas une nécessité en effet. Je clos.
