### ISSUE TITLE
Nom français ou anglais pour les nouvelles colonnes ?

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/UsersHub#142]
Dans la continuité des ajouts de champs `JSONB` permettant d'ajouter des données additionnelles et personnalisées en bdd, je souhaiterai ajouter un tel champ à la table bib_organismes (qui me permettra notamment de gérer les correspondances avec les personnes morales issues de VisioNature).

Mais pour ça, se pose la question du nom du champ, `champs_addi` comme dans `t_roles` ou `additional_data` comme c'est maintenant la norme dans GeoNature (choix que personnellement je priviligie).

**Comment by DonovanMaillard** [comment]
Le français est un héritage mais la tendance pour ce qui est nouveau était d'aller vers l'anglais sauf erreur...  je trouve que additional data est très clair et j'irais vers ca partout personnellement...

**Comment by camillemonchicourt** [comment]
Oui on peut commencer à aller vers ça.
Je partirai donc sur ``additional_data``.

**Comment by lpofredc** [comment]
Merci, la question se posait surtout pour des questions de cohérences au sein d'une même application. 

Je prépare donc une PR pour l'ajout d'un champ JSONB `additional_data` sur `bib_organismes`.

**Comment by lpofredc** [comment]
Modification apportée à https://github.com/PnX-SI/UsersHub-authentification-module/commit/71a14ca6f2de4d67d98c808a28c48d0e3f9aa557
