### ISSUE TITLE
Migration vers 2.2.1 - un impact pour la conf apache en sous-domaine ?

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/UsersHub#144]
Bonjour,
Je tente une montée de version vers UsersHub 2.2.1 depuis la v2.1.3.

Après avoir suivi les notes de version, le site ne fonctionne plus. Voilà l'erreur dans `usershub.log` : 

```
[ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/geonatureadmin/usershub/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/geonatureadmin/usershub/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 167, in handle_request
    listener.getsockname(), self.cfg)
  File "/home/geonatureadmin/usershub/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 193, in create
    path_info = path_info.split(script_name, 1)[1]
IndexError: list index out of range
```

La seule partie que j'ai ignoré est celle concernant l'accès à usershub sur un préfixe vu que j'y accède sur un sous-domaine _(comme dans la documentation de GeoNature : https://docs.geonature.fr/conf-apache.html, avec un fichier /etc/apache2/**sites-available**/usershub.conf et non dans /etc/apache2/**conf-available**/usershub.conf_ ).

---
> **Révision de la configuration Apache :**
> Le script d’installation `install_app.sh` aura installé le fichier `/etc/apache2/conf-available/usershub.conf` permettant de servir UsersHub sur le préfixe `/usershub`.
> Vous pouvez utiliser ce fichier de configuration soit en l’activant (`sudo a2enconf usershub`), soit en l’incluant dans la configuration de votre vhost (`IncludeOptional /etc/apache2/conf-enabled/usershub.conf`).
> Si vous gardez votre propre fichier de configuration et que vous servez UsersHub sur un préfixe (typiquement `/usershub`), assurez vous que ce préfixe figure bien également à la fin des directives `ProxyPass` et `ProxyPassReverse` comme c’est le cas dans le fichier `/etc/apache2/conf-available/usershub.conf`.

---
Il y a quelque chose à modifier dans la conf apache même sans utiliser de préfixe ? Ou l'erreur n'a rien à voir avec cette conf ? 
Merci d'avance pour votre aide !

**Comment by bouttier** [comment]
Bonjour,
Je confirme qu’il s’agit bien d’un problème lié à la gestion des préfixes.
Pouvez-vous vérifier la valeur de la variable ``URL_APPLICATION`` dans le fichier de configuration de UsersHub ? Si vous servez UsersHub sans préfixe, cette variable doit également ne pas faire figurer de préfixe.

**Comment by Splendens** [comment]
Merci, c'était bien ça ! Je n'avais pas fait attention au fait que le fichier de conf de UH était remplacé lors de cette migration.
