### ISSUE TITLE
[2.2.1] erreur : - The CSRF tokens do not match. 

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/UsersHub#148]
Bonjour,

Après la montée en version de Usershub en 2.2.1 (https://github.com/PnX-SI/GeoNature/issues/1516), j'ai des problèmes pour réaliser certaines actions dans l'appli.

J'accède à UH et je me connecte sans problème, et je peux supprimer des entrées, Par contre, dès que je tente d'ajouter ou de modifier un utilisateur ou un organisme par exemple, il y a l'erreur `- The CSRF tokens do not match.` qui s'affiche dans un bandeau rouge. 

J'ai bien essayé dans 2 navigateurs différents et dans des fenêtres de navigation privée au cas où cela puisse venir des cookies, mais cela n'a fait aucune différence.

Je ne vois pas d'erreur dans la console du navigateur (mais peut être que je ne regarde pas où il faut...). Quelqu'un a déjà eu un problème similaire ? Cela pourrait venir d'une mauvaise configuration (Apache  et/ou Usershub) ?

**Comment by jbrieuclp** [comment]
Le CSRF c'est une truc de backend et il y a de forte chance que ça vienne de WTForm. 
Et dans ce cas il faudrait virer ou adapter cette protection à voir ici : [exclude-views-from-protection](https://flask-wtf.readthedocs.io/en/0.15.x/csrf/#exclude-views-from-protection)

**Comment by Splendens** [comment]
Si cela vient du backend, quelqu'un d'autre a également ce problème avec la dernière version de Usershub ?
Ou je suis seule et faut chercher autre part ?

**Comment by Splendens** [comment]
Au cas où, j'ai tenté avec une installation neuve de GN 2.8.1 et UH 2.2.1, et il y a exactement le même problème.
Par contre, tout fonctionne bien lorsque UH est accessible sur une URL de type `geonature.blabla.fr/usershub`. Donc Usershub 2.2.1 ne fonctionne pas sur son propre sous domaine.

**Comment by bouttier** [comment]
Bonjour,
L’application UsersHub fonctionne chez moi sans soucis avec la conf apache suivante :
```
<Location />
    ProxyPass http://127.0.0.1:5001/
    ProxyPassReverse http://127.0.0.1:5001/
</Location>
```
Et avec le configuration suivante :
```
URL_APPLICATION = 'http://mon-domaine.fr'
URLS_COR = ['http://mon-domaine.fr']
```
Êtes-vous sûr d’avoir correctement renseigné le paramètre ``URLS_COR`` ?

**Comment by bouttier** [comment]
J’ai rajouté dans la documentation [la configuration Apache nécessaire pour l’installation sur un sous-domain](https://usershub.readthedocs.io/fr/develop/installation.html#installation-de-usershub-sur-un-sous-domaine).

**Comment by bouttier** [comment]
Pour ``URLS_COR``, en fait j’ai l’impression que Flask-CORS n’est plus utilisé mais cela n’a été ni retiré des requirements, ni de la config ………

**Comment by bouttier** [comment]
Utilisation de ``flask_cors`` retiré par d146b801120038b69bdadd6f0b6d451dd1ec6469
Je vais retirer le paramètre ``URLS_COR`` finalement.

**Comment by gildeluermoz** [comment]
> Si cela vient du backend, quelqu'un d'autre a également ce problème avec la dernière version de Usershub ?
> Ou je suis seule et faut chercher autre part ?

J'ai exactement le même soucis en 2.2.1

**Comment by camillemonchicourt** [comment]
Avec les ajouts dans la documentation, avez-vous toujours des soucis ?
Sinon il nous faudrait votre configuration pour identifier ou reproduire le problème.

**Comment by gildeluermoz** [comment]
Oui, idem. Si tu parles de la conf apache, j'ai bien celle proposée.
Le soucis ressemble à ça : https://issueexplorer.com/issue/wtforms/flask-wtf/424
Ca marche en dev mais pas toujours en prod une fois déployé...

J'ai testé plusieurs valeur pour `URLS_COR`
URLS_COR = ["http://localhost:5000","http://localhost:5001","http://127.0.0.1:5001","https://usershub.mondomaine.fr","http://usershub.mondomaine.fr"]
Ca ne fonctionne pas

J'ai exploré cette piste maiss ans succès : https://nickjanetakis.com/blog/fix-missing-csrf-token-issues-with-flask

Je fais bien `sudo systemctl restart usershub.service` à chaque changement.

Je sèche...

**Comment by bouttier** [comment]
Bonjour,
N’ayant pas reproduit de mon côté, pouvez-vous m’indiquer :
- les URLs précises du backend qui lèvent cette erreur
- vérifier dans le contenue de la requête la présence ou l’absence  dans les paramètres d’une entrée ``csrf_token``
- décrire les étapes suivit pour reproduire l’erreur (se rendre sur telle page, cliquer sur tel bouton, etc.)
- la valeur de ``URL_APPLICATION`` dans votre configuration UsersHub
- votre configuration Apache
Merci

**Comment by gildeluermoz** [comment]
Elie,
Je te transmets tout ça message privé.

**Comment by gildeluermoz** [comment]
en complément, l'erreur.
Sachant qu'il n'y a pas de trace dans /var/log/usershub.log. Ni dans la
console.
[image: image.png]


Le lun. 13 déc. 2021 à 10:03, Élie Bouttier ***@***.***> a
écrit :

**Comment by bouttier** [comment]
Toujours pas reproduit … mais peut-être un soucis avec ``APPLICATION_ROOT`` peux-tu essayer avec la develop ou alors avec ce patch be24c57e59cb4d336fc55a75812968ae999e0c1f ?

**Comment by gildeluermoz** [comment]
Bingo !
Ca marche avec le patch sur APPLICATION_ROOT. Bien vu ! Et grand merci.
Tu postes le correctif dans le ticket ou tu veux que je le fasse ?

Le lun. 13 déc. 2021 à 13:02, Élie Bouttier ***@***.***> a
écrit :

**Comment by camillemonchicourt** [comment]
OK super.
Cette correction sera incluse dans la prochaine release de UsersHub, à venir bientôt.

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 2.2.2.
