### ISSUE TITLE
2.2.1 - Impossible de modifier un rôle associé à une application

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/UsersHub#152]
- Je suis dans une application, je veux modifier le profil d'un utilisateur (application/update/role_profil/290/28)
- Je modifie le rôle, j'enregistre
- Rien ne se passe, aucun message et aucun changement

**Comment by gildeluermoz** [comment]
Je n'ai pas le même comportement :  sur `.../application/update/role_profil/9/2`
Si je modifie le profil du rôle choisi, j'enregistre : la modif est bien prise en compte.
Est-ce que tu fais autre chose ?

J'ai choisi un groupe. Je n'ai pas d'utilisateur qui ne sont pas dans un groupe.
Je suis en 2.2.1 avec le patch proposé par Elie https://github.com/PnX-SI/UsersHub/commit/be24c57e59cb4d336fc55a75812968ae999e0c1f

**Comment by camillemonchicourt** [comment]
J'ai déployé la ``develop`` pour tester et j'ai toujours le même soucis.
Et quand j'essaie de créer un nouvel utilisateur, j'ai le message ``- The CSRF tokens do not match.`` donc je dois avoir un autre soucis.
On va creuser.

**Comment by camillemonchicourt** [comment]
OK en fait c'est que j'avais pas bien fait la MAJ, c'est OK maintenant et on en a profité pour intégrer ces corrections dans une release 2.2.2 qui vient de sortir.
