### ISSUE TITLE
Accès usershub impossible aprés mise à jour 2.1.3 vers 2.2.0

### ISSUE THREAD

**Issue by maki2a** [PnX-SI/UsersHub#155]
Bonjour,
Dans le cadre d'une migration geonature 2.7.5 vers 2.8.0, j'ai commencé par mettre à jour usershub
Version initiale 2.1.3
Après migration vers 2.2.0 j'ai un message d'erreur sur la page de connexion:
"Paramètres de connexion invalides" après avoir tapé mon login/mot de passe
Ci-dessous une capture d'écran de la console web
![console-web](https://user-images.githubusercontent.com/91948895/151534228-e1941c04-8de7-4adb-9e91-c1c10625b090.JPG)
Je ne trouve pas de solution même si :
- j'autorise le chargement du contenu mixte sur le navigateur.
- je rajoute mon utilisateur avec un accès administrateur sur l'application usershub dans la table utilisateurs.cor_role_app_profil
-(il était déjà dans le groupe administrateurs)

Merci pour votre aide
pierre-ange martos
DREAL de Corse

**Comment by camillemonchicourt** [comment]
Je dirai un problème de configuration Apache ou de configuration.
Ou sinon il faut aller au bout de la mise de GeoNature (car c'est lui qui se charge de la mise à jour du schéma UTILISATEURS désormais suite au passage à Alembic).

Par ailleurs, quand on met à jour, il n'est pas utile (ni souhaité) d'installer les versions intermédiaires. Il faut direct passer à la version la plus récente (2.2.2 actuellement).

Idem pour GeoNature, il faut passer directement à la version récente (en faisant par contre bien attention aux notes de version intermédiaires, surtout qu'elles sont costauds pour passer la 2.8 et la 2.9).

**Comment by maki2a** [comment]
Merci pour la réponse,
Je recommence le tout( merci aux points de restauration!)
Et je vais migrer des versions geo 2.7.5, taxhub 1.8.1 et userhub 2.1.3 vers
geo 2.9, taxhub1.9.4 et usershub 2.2.2
Bonne journée

**Comment by camillemonchicourt** [comment]
OK ces mises à jour sont assez compliquées car il y a pas mal de changements (passage à Alembic, à systemd, etc...) pour simplifier les suivantes et améliorer le socle des composants techniques.
