### ISSUE TITLE
Ajouter champs ACTIF sur t_roles

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/UsersHub#16]
Pouvoir Activer/Desactiver un utilisateur sans le supprimer de la BDD.

**Comment by gildeluermoz** [comment]
A voir pour quel usage ?
Il faut en effet se servir de ce champ qq part.
 Actuellement, on peut supprimer login et pass d'un utilisateur, ceci le désactive de fait pour toute authentification. On peut donc considérer qu'un utilisateur sans login n'est plus actif. C'est moins clair, moins simple qu'un boolean mais ça fonctionne et ça peut être utilisé pour de nouvelles foànctionnalités ou pour des filtres.

**Comment by gildeluermoz** [comment]
DONE : https://github.com/PnEcrins/UsersHub/commit/24290545656e65c8228e8695b68ec330d9b72040

**Comment by camillemonchicourt** [comment]
OK super. 
Reste à ajouter le champs dans les formulaires d'édition des Rôles. 
Dans les listes des Rôles, ça vaudrait le coup d'afficher différemment les rôles inactifs.

Et pour toutes les vues et routes d'authentification, il faudrait ajouter ``where t_roles.active = TRUE``.
Ce champs permet de désactiver le compte d'un utilisateur (ou groupe ?) sans avoir à le supprimer de la BDD ni avoir à supprimer son MDP.

Par contre il peut rester dans des listes (d'observateurs notamment). 
Il peut rester dans des groupes mais son compte étant inactif, il ne doit pas bénéficier des accès donnés au groupe.

**Comment by gildeluermoz** [comment]
Un peu là : 
https://github.com/PnEcrins/UsersHub/commit/7f5133d97852642fe6f32a4c495021188f5358eb
et  surtout là :
https://github.com/PnEcrins/UsersHub/commit/ea3529e90ff8f3f1ee5d8073cefd37b62827be9c

**Comment by camillemonchicourt** [comment]
En place depuis la v2.
