### ISSUE TITLE
Paramètres de connexion invalides

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/UsersHub#167]
Bonsoir,

Après installation des certificats SSL et configuration du frontend d'après la doc du site, tout fonctionne sauf l'accès à https://...../usershub/ il m'affiche "Paramètres de connexion invalides"
Dans l'inspecteur du navigateur Chrome (onglet console) de la page j'ai cette erreur 

> Mixed Content: The page at 'https://geonat.structure.fr/usershub/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://geonat.structure.fr/usershub/pypn/auth/login'. This request has been blocked; the content must be served over HTTPS.

Avez-vous une idée de ce que j'ai manqué sur la configuration ?

Merci pour votre aide.

**Comment by camillemonchicourt** [comment]
Avez-vous bien modifié le paramètre ``URL_APPLICATION`` dans le fichier ``config/config.py`` ?
Après modification d'un paramètre, il faut recharger (ou redémarrer) l'application avec la commande ``systemctl reload usershub``.

Voir https://github.com/PnX-SI/UsersHub/issues/151

**Comment by naidinp** [comment]
je l'avais modifié mais pas pensé a redémarrer le service.

Merci pour l'aide.
Belle soirée - je ferme le ticket.

**Comment by camillemonchicourt** [comment]
Oui c'était pas indiqué dans la doc, donc ça se devine pas.
Je viens de le préciser dans la doc - https://github.com/PnX-SI/UsersHub/pull/168/files

**Comment by naidinp** [comment]
Super merci.
