### ISSUE TITLE
Affichage membres Liste

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/UsersHub#169]
Bonjour,

je voudrais afficher les membres de la Liste **_obsocctax_** (fournie avec l'installation) mais je rencontre l'erreur suivante et ceci après la modification de la requête comme indiqué dans le post intitulé "[Erreur] Affichage de la liste des membres associés à une liste #165"  :

`{"type": "Exception", "msg": "AttributeError(\"type object 'TRoles' has no attribute 'id_liste'\")"}`

Après la correction j'ai relancé le backend avec _sudo systemctl restart geonature , j'ai fait aussi un buil du frontend et redémarré le serveur.

J'ai oublié quelque chose certainement. 

Merci pour votre aide.

**Comment by camillemonchicourt** [comment]
Oui cela devrait être intégré et donc corrigé dans la prochaine version de UsersHub.
