### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by andyolinga** [PnX-SI/UsersHub#187]
j'ai iinbstalle en suivant le guide d'installation mais quand je saisi l'url du fichier : "config/settings.ini" dans mon navigateur on me renvoie le message d'erreur : "Hmm. We’re having trouble finding that site.

We can’t connect to the server at mon_url.fr.

If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web." quelle est le probleme?

**Comment by camillemonchicourt** [comment]
Ce fichier n'a pas d'URL et n'est pas accessible en HTTP.
C'est un fichier de configuration présent dans les fichiers qui composent l'application, dans le dossier que vous avez téléchargé du code source de UsersHub.

**Comment by andyolinga** [comment]
s'il te plait apres installation comment lancer l'application ?

**Comment by camillemonchicourt** [comment]
Si l'installation a été suivie complètement et correctement, elle est accessible à l'adresse de votre serveur dans un navigateur web, selon la configuration Apache que vous avez faites : https://usershub.readthedocs.io/fr/latest/installation.html#configuration-apache

**Comment by andyolinga** [comment]
j'ai rien configure sur apche j'ai simplement suit l'installation et j'ai essayer de l'ouvrir sur mon navigateur mais riens

**Comment by camillemonchicourt** [comment]
L'installation indique de faire une configuration Apache.
