### ISSUE TITLE
Afficher les champs additionnels liés à l'utilisateur dans l'interface

### ISSUE THREAD

**Issue by ch-cbna** [PnX-SI/UsersHub#197]
### Version
develop > 2.4.0

### Cas pratique
J'ai un accès à UsersHub mais pas à la BDD. Je souhaite voir quel organisme a été renseigné par un nouvel inscrit dans le cas où le rattachement manuel à un organisme de la base n'a pas été fait.

Lorsqu'on a accès à la BDD, on peut retrouver cette information dans `utilisateurs.t_roles.champs_addi`.

### Comment reproduire ?
Réaliser une demande de création de compte en renseignant le champ "Organisme". Valider cette demande de création de compte. Visualiser les informations de ce nouvel utilisateur sur UsersHub.

### Solution envisagée
Afficher l'organisme saisi par le nouvel utilisateur lorsque `utilisateurs.t_roles.id_organisme` n'est pas renseigné.

### Code info_user.html
 
```
-- Modif L6
{%set is_organisme = organisme is not none and organisme['nom_organisme'] != '' %}

-- Ajout
{%set is_champs_addi = user['champs_addi']['organisme'] is not none
and user['champs_addi']['organisme'] != '' %}

-- Modif L29
            {% if is_organisme %}
                <br /><strong>Organisme :</strong> {{organisme.nom_organisme}}
            {% elif is_champs_addi %}
                <br /><strong>Organisme :</strong> {{user['champs_addi']['organisme']}}
            {% endif %}
```

### Rendu
![image](https://github.com/PnX-SI/UsersHub/assets/102586824/a06fbb55-b7cc-427a-aec5-6bc0194e5975)

**Comment by camillemonchicourt** [comment]
L'idée n'était pas plutôt d'afficher tous les champs additionnels de manière générique ?
Et pas spécifiquement du champs additionnel de l'organisme.

**Comment by ch-cbna** [comment]
Effectivement ce serait plus intéressant.

**Comment by ch-cbna** [comment]
En prenant en compte les différents types de données possibles d'un JSON (notamment les tableaux et objets imbriqués) , voici le rendu de l'affichage des champs additionnels (où "Name", "Methods" et "Ingredients" sont des champs additionnels) : 
![image](https://github.com/PnX-SI/UsersHub/assets/102586824/fc9a2ee0-41c8-4e68-89a5-cf1de8c869f5)

Une PR arrive prochainement.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.4.1.
