### ISSUE TITLE
Bug affichage du prénom et du nom sur la fiche utilisateur

### ISSUE THREAD

**Issue by ch-cbna** [PnX-SI/UsersHub#198]
### Version
develop > 2.4.0

### Visuel actuel
![image](https://github.com/PnX-SI/UsersHub/assets/102586824/47733563-268f-4915-85ca-6af7fb9d85f2)

### Code app/t_roles/routes.py
```
-- Add L271
`fullname = buildUserFullName(user)`

-- Add L278
`fullname=fullname,`
```

### Code app/templates/info_user.html
```
-- Update L16
<h3>Utilisateur "{{fullname}}"</h3>
```

### Rendu
![image](https://github.com/PnX-SI/UsersHub/assets/102586824/74e6b459-0aa8-433b-b83c-f174fad79203)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.4.1.
