### ISSUE TITLE
usershub.readthedocs.io n'est pas à jour

### ISSUE THREAD

**Issue by vprunet** [PnX-SI/UsersHub#200]
Bonjour, 

La doc publiée sur readthdocs.io n'est pas à jour avec celle enregistrée sur github.
Exemple : le changelog, dans lequel usershub 2.4.0 n'est pas listé.

**Comment by camillemonchicourt** [comment]
Corrigé par https://github.com/PnX-SI/UsersHub/pull/205

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.4.1.
