### ISSUE TITLE
Afficher tous les champs de t_roles dans l'interface "Utilisateur"

### ISSUE THREAD

**Issue by ch-cbna** [PnX-SI/UsersHub#203]
**Version**
2.4.0

Afin d'avoir une meilleur gestion des utilisateurs lorsque l'on n'a pas accès à la base de données, il est intéressant de disposer de tous les champs de la table `utilisateurs.t_roles` dans l'interface "Utilisateur" (user/info/<id>) de UsersHub.

**Rendu**
![image](https://github.com/PnX-SI/UsersHub/assets/102586824/e86d18b9-ab46-4147-801b-fd226602235c)

**Comment by camillemonchicourt** [comment]
Fait dans la 2.4.1.
