### ISSUE TITLE
UsersHub V2 - Refonte

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/UsersHub#28]
Une refonte de UsersHub en V2 est amorcée dans une branche dédiée : https://github.com/PnEcrins/UsersHub/tree/uhv2

Cette refonte vise à : 
- Moderniser UH en basculant sur de nouvelles technologies (Python 3, Flask, Bootstrap, Jinja, SQLAlchemy, Javascript)
- Intégrer la gestion des tags et du CRUVED (nécessaire à GeoNature V2)

La refonte est réalisée par @Laumond11u

**Comment by Laumond11u** [comment]
Evolution du modèle de la base de données de la V1 à la V2
![schema utilisateurs v1](https://user-images.githubusercontent.com/37363539/41416893-3a21ad38-6fec-11e8-88c6-2b021334bb22.png)
![schema utilisateurs v2](https://user-images.githubusercontent.com/37363539/41416897-3d395a2a-6fec-11e8-9957-c1d348385520.png)

**Comment by camillemonchicourt** [comment]
Le travail de refonte est bien avancé. 
Voir le rapport de stage de @Laumond11u : http://geonature.fr/documents/2018-06-usershub-v2-rapport-stage-Gabin-Laumond.pdf
Et sa présentation : http://geonature.fr/documents/2018-06-usershub-v2-soutenance-stage-Gabin-Laumond.pdf

**Comment by camillemonchicourt** [comment]
Cette refonte se basait initialement sur un concept central et générique de "tags". 
Elle visait aussi à intégrer le CRUVED en s'appuyant sur ces tags. 

En avançant, cela a soulevé plusieurs fois des interrogations. 
A l'usage on se rend notamment compte que la table qui gérait le CRUVED est insuffisante pour GeoNature mais qu'elle est trop complexe pour gérer les droits d'autres applications. 

Il est donc décidé de réintégrer le CRUVED dans GeoNature : https://github.com/PnX-SI/GeoNature/issues/517

Les applications restent ainsi plus indépendants de UsersHub qui recentré sur son rôle principal qui est de gérer des utilisateurs, leur compte, leur appartenance à des groupes et leurs profils par rapport aux différentes applications. 
Les permissions simples et statiques (comme dans TaxHub, UH ou Patrimoine bati) comme les permissions complexes et dynamiques gérées dans la BDD (GeoNature ou Geotrek) restent à gérer au niveau de chaque application.

- On garde ``t_roles`` (regroupant utilisateurs et groupes, éventuellement à éclater plus tard)
- On garde ``t_applications`` en y ajoutant un code_application (https://github.com/PnEcrins/UsersHub/issues/54)
- On transforme ``t_menus`` en ``t_listes`` accompagné de ``cor_role_liste``
- On abandonne la notion trop générique de "tags"
- On ajoute une table ``t_profils``, accompagnée de ``cor_application_profil`` (pour définir quels profils sont utilisables par quels applications) et ``cor_role_application_profil`` (pour stocker les profils des rôles par application)

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnEcrins/UsersHub/commit/5f946375213e18269435cd5e2279b57e8ddba72e
