### ISSUE TITLE
Créer une API permettant de créer des utilisateurs

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/UsersHub#47]

**Comment by camillemonchicourt** [comment]
OK vu la route ``get_one_t_roles``.

**Comment by amandine-sahl** [comment]
La pull request #80 intègre le travail réalisé par @joel.clement

Ajoute les fonctionnalités suivante : 
* Changement de mot de passe
* Ajouter un utilisateur
* Mette à jour un utilisateur
* Changer le niveau de droit d'un utilisateur
* Rajouter le droit sur une application à un utilisateur existant

![userhub_api](https://user-images.githubusercontent.com/3088650/54833451-6f851280-4cbe-11e9-8c73-4809638fc9c2.jpg)

**Comment by camillemonchicourt** [comment]
Fait dans la 2.1.0
