### ISSUE TITLE
UHV2 - Formulaire Utilisateurs - affichage des groupes (et des listes) -

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/UsersHub#57]
Dans le formulaire, on peut rattacher un utilisateur à un ou pls groupes.
Actuellement le fonctionnement n'est pas assuré au moins lors d'un update, les groupes de l'utilisateur ne sont pas remplis.
Décider s'il faut permettre l'affectation d'un utilisateur à des groupes depuis le formulaire utilisateurs ou pas (seulement depuis le formulaire groupe). Si oui corriger le fonctionnement.
On peut aussi afficher (en lecture seule) les groupes auxquels un utilisateur appartient.

Même logique pour les listes.

**Comment by camillemonchicourt** [comment]
Le soucis a été corrigé.
