### ISSUE TITLE
Chemin de migration depuis Usershub 1.2

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/UsersHub#59]
Salut,

En vue de la migration vers GeoNature V2 et de son module Usershub, disposez vous d'une documentation et d'outillage pour celle-ci (en plus des scripts update1.xt01.y.sql) ?
Pour mémoire nous utilisons actuellement au PNM Usershub 1.2.0 pour la gestion des utilisateurs de l'application [autorisation de circulation](https://github.com/PnMercantour/autorisations_circulation).

Merci

**Comment by camillemonchicourt** [comment]
Il te faut commencer par migrer sur la dernière version 1.x (1.3.3 actuellement), en suivant les notes de versions et scripts de migration de la BDD successifs : https://github.com/PnEcrins/UsersHub/releases

Ensuite, le développement de UserHub v2 avance bien dans sa branche dédiée (``uhv2``) et @gildeluermoz a bien avancé sur le script de migration de la 1.3 vers la future 2.0 (pas encore sortie) : https://github.com/PnEcrins/UsersHub/blob/uhv2/data/update_1.3.1to2.sql

La V2 en cours de développement est disponible ici : http://demo.geonature.fr/usershub2/ (admin / admin).

Toute la partie CRUVED a été réintégrée dans GeoNature (https://github.com/PnX-SI/GeoNature/issues/517) pour bien garder UsersHub générique et centré sur la gestion des utilisateurs, mais pas sur leurs permissions applicatives qui doivent être gérées au sein de chaque application.
La version 2 de UsersHub prend cela en compte.

Nous préparons une RC4 de GeoNature qui inclut cette réintégration du CRUVED dans GeoNature, ainsi que son interface d'administration.

**Comment by samuelpriou** [comment]
Merci pour ces informations.
Du coup qu'en est il des permissions applicatives pour Geotrek-admin ? Je crois me rappeler que vous gérer ses utilisateurs via usershub ?
Cela veut il dire que les applications qui utilisent usershub (Geotrek-admin, autorisation de circulation...) doivent être réécrites ?

**Comment by camillemonchicourt** [comment]
Non justement, on s'est notamment basé sur le fonctionnement de Geotrek où les permissions applicatives sont bien gérées dans Geotrek-admin où tu donnes des actions possibles à des utilisateurs ou groupes d'utilisateurs.
UsersHub te permet juste de définir des utilisateurs avec un login/mdp et de les associer à des groupes.
Ce que peuvent faire chaque utilisateurs ou groupes d'utilisateurs est bien défini au niveau de Geotrek-admin et de sa propre BDD.

**Comment by samuelpriou** [comment]
Ok, du coup on conserve dans Usershub les niveaux de droits allant de 0 à 6
0 - aucun droit
1 - utilisateur
...
6 - administrateur

**Comment by camillemonchicourt** [comment]
Voir documentation : https://usershub.readthedocs.io/fr/latest/migration-v1v2.html
