### ISSUE TITLE
UH2 - Supprimer champs inutiles

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/UsersHub#78]
Il reste des champs de la V1 dans la table ``utilisateurs.t_roles`` qui ne sont plus utilisées et donc qu'il vaudrait mieux supprimer : 
- ``pn``
- ``id_unite``
- ``session_appli``

A voir si cela ne pose pas de problème de rétro-compatibilité, mais dans ce cas, il vaut mieux que ceux qui avaient dejà UH1 se gardent ces champs mais de pas les coller aux nouveaux utilisateurs.

**Comment by gildeluermoz** [comment]
oui ils sont utilisés en V1 par certaines applications.
Effectivement on peut ne pas les créer en V2 (en vérifiant bien qu'ils ne sont utilisés nulle part)
Mais ne surtout pas les droper dans un script d'update de la base.

**Comment by camillemonchicourt** [comment]
OK - https://github.com/PnX-SI/UsersHub/commit/b69f6a269a184d800eeae085f31df4fa3521b55a
