### ISSUE TITLE
Formulaire Role d'une application - Ordre alphabétique

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/UsersHub#81]
Quand on veut ajouter un rôle à une application (application/add/role_profil), la liste des rôles est difficile à utiliser car non triée par ordre alphabétique.

**Comment by DonovanMaillard** [comment]
Valable pour toutes les listes, nomenclatures des méta-données etc ;)

**Comment by gildeluermoz** [comment]
Je l'ai fais dans mon gas. ca se fais au niveau model 
https://github.com/gildeluermoz/gas/commit/811ee1b60417d0307ed81af6b0a102564e4863e4
ou directement dans les routes.
https://github.com/gildeluermoz/gas/commit/aa29534d0bbc2a937f138da2bd2edb7fd904bc07

**Comment by camillemonchicourt** [comment]
https://github.com/PnX-SI/UsersHub/commit/a392dd15e40ae26a1eea416f85debadfa60e0561

**Comment by amandine-sahl** [comment]
Désolée j'avais pas fait attention au message de Gil

**Comment by gildeluermoz** [comment]
Pas de soucis, c'était juste pour mémoire si je devais m'y coller.
Mais comme tu l'as fais, c'est parfait.
Mais je crois qu'il faut faire un tour de l'appli et regarder tous les affichages de liste déroulantes. Ce n'est pas trop trié il me semble.
