### ISSUE TITLE
API - create temp_user mail

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/UsersHub#84]
Salut,
L'envoi de mail sur cette action n'est pas encore développé, l'idée c'est d'utiliser Flask-Mail (sa dernière version date de 2014) ou une autre lib ?

**Comment by camillemonchicourt** [comment]
Finalement les emails sont envoyés par l'application qui utilise l'API. 
GeoNature dans notre cas et c'est bien Flask-mail qui a été utilisé.
