### ISSUE TITLE
BDD mère et BDD fille

### ISSUE THREAD

**Issue by skerdreuxNaomis** [PnX-SI/UsersHub#88]
Bonjour,

J'ai un doute sur les notions de BDD mère et BDD filles.
La BDD mère correspond à la base de données renseignée dans le fichier config/settings.ini de usershub ? 
et la BBD fille correspond à/aux bases de données renseignées dans le fichier config/dbconnexions.json ? 
du coup dans ce dernier cas est-il normal de disposer dans le fichier dbconnexions.json de la BDD mère ainsi que la BDD fille ? 

et dernière question : si on applique des migrations successives on doit uniquement les appliquer sur la BDD mère ? (sauf indications précises comme le passage de la 1.2.1 vers la 1.3.0)

Merci d'avance pour vos réponses !
Sylvain.

**Comment by camillemonchicourt** [comment]
Dans quel contexte ?

Avec GeoNature 2 par défaut le schéma "utilisateurs" de UsersHub est dans la BDD de GeoNature donc il n'y a pas de mère et de fille. Dans UsersHub V2 on n'utilise plus le fichier dbconnexions.json de mémoire.

Dans un contexte simple il n'y a pas de BDD mère et fille. C'est uniquement dans le cas de réplication du schéma "utilisateurs" dans des BDD tiers

**Comment by skerdreuxNaomis** [comment]
c'est dans le contexte d'une migration v1 vers v2.
je comptais passer les scripts de la v1 (1.2 jusqu'à 1.3.1) quand je suis tombé sur le script 1.2.1 vers 1.3.0 avec une partie BDD mère et une partie BDD fille. 

En suivant votre réponse il ne devrait pas y avoir en théorie de schéma "utilisateurs" dans la BDD de GeoNature v1.9.1 ?

**Comment by camillemonchicourt** [comment]
OK dans un cas simple et par défaut dans GeoNature v1 on installait aussi le schéma "utilisateurs" dans la BDD GeoNature sans BDD fille ni mère. 
Mais ça c'est à vous de voir et vérifier votre contexte d'utilisation.

Mais à priori votre installation est comme ça et vous n'avez qu'à appliquer les migrations de la BDD mère car vous n'avez pas de BDD filles (pas de réplication dans une autre BDD)
