### ISSUE TITLE
info organisme n'est plus accessible dans la V2.1.0

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/UsersHub#90]
Dans l'onglet organismes quand on clique sur "voir" (icône représentant un oeil) j'arrive sur une page vide avec cette erreur :
 `{"type": "Exception", "msg": "AttributeError(\"type object 'TRoles' has no attribute 'nom_organisme'\",)"}`

Cela vient du `order_by="nom_organisme"` car ce champ n'existe pas dans la table TRoles Et qui est à remplacer par "nom_role" plutôt. 
Cf extrait de code du fichier \home\geonatureadmin\usershub\app\bib_organismes\route.py

```def info(id_organisme):
    org = Bib_Organismes.get_one(id_organisme)
    q = TRoles.get_all(
        as_model=True,
        params=[
            {"col": "active", "filter": True},
            {"col": "id_organisme", "filter": id_organisme},
        ],
        order_by="nom_organisme",
    )
    users = [data.as_dict_full_name() for data in q]

    return render_template("info_organisme.html", org=org, users=users)```

**Comment by camillemonchicourt** [comment]
Corrigé dans 2.1.2
