### ISSUE TITLE
Deux fois la création de temps user dans le fichier update_2.0.3to2.1.0

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/UsersHub#94]
ici et ici
https://github.com/PnX-SI/UsersHub/blob/b7cea35b45f84e17772c1ebfd1b46fb8f5e71f19/data/update_2.0.3to2.1.0.sql#L19-L38

https://github.com/PnX-SI/UsersHub/blob/b7cea35b45f84e17772c1ebfd1b46fb8f5e71f19/data/update_2.0.3to2.1.0.sql#L59-L83

Le premier n'a pas id_application le second oui ???

**Comment by TheoLechemia** [comment]
Corrigé
